#----HEADER-------------------------------------------------------------------------------------------------------------
# Author:  USERNAME
# Date:    DATE
# Purpose: For LBD - read in Google Sheet with Literature and Report extractions. Process and Resample polygons for each vaccine prefix.
#              Added during Wrapper rewrite DATE: read in MICS report extractions for surveys whose report tabulations differ too greatly
#              from the estimates generated by the wrapper. Decisions made by the "Decider"
# Run:     source("FILEPATH")
# Run Job: qsub -l m_mem_free=20G -P proj_geo_nodes -q geospatial.q -l fthread=12 -l archive=TRUE -N SNTS_Hepb3 FILEPATH 
#          -e s FILEPATH --indicator dpt3_cov --run_date RUN_DATE

#***********************************************************************************************************************
#----SETUP--------------------------------------------------------------------------------------------------------------
### load packages
source("FILEPATH")
invisible(load_packages(c("proto", "findpython", "getopt", "argparse", "data.table", "magrittr", "survey", "binom", "parallel", "plyr", "dplyr", "haven",
                         "rgeos", "raster", "rgdal", "dismo", "gbm", "foreign", "doParallel", "grid", "gridExtra", "gtools", "ggplot2",
                         "sf", "fasterize", "assertthat")))
message("Successfully loaded packages")

### set username
username <- 'USERNAME'
#---LOAD PACKAGES --------------------------------------------------------------------------------------------------------
core_repo      <- sprintf('FILEPATH'); setwd(core_repo)  
indic_repo     <- sprintf('FILEPATH')
commondir      <- sprintf('FILEPATH')
package_list   <- c(t(read.csv(sprintf('FILEPATH'), header=FALSE)))

source(paste0('FILEPATH'))
source(paste0("FILEPATH"))
source(paste0("FILEPATH"))
source('FILEPATH')

mbg_setup(package_list=package_list, repos=core_repo)

source('FILEPATH')
str_match <- stringr::str_match

#----LOAD ARGUMENTS-----------------------------------------------------------------------------------------------------
### setup arguments
parser <- ArgumentParser()
parser$add_argument("--indicator", help="Enter antigen-dose combination, e.g. `hepb3`, `dpt3`, `hib3`")
parser$add_argument("--run_date", help="Enter run date of input data, `2019_12_18_10_39_35`, for example")

### save job args as objects
args <- parser$parse_args()
message(args)
list2env(args, environment()); rm(args)

#---SET VARIABLES---------------------------------------------------------------------------------------------------------

# Matched Regions and Titles, don't change order
ad0_map_regions       <- c("vax_cssa", "vax_name", "vax_caeu", "vax_wssa", "vax_seas", "vax_sssa", "vax_ansa", "vax_crbn", "vax_ctam", "vax_eaas", "vax_soas", "vax_trsa", "vax_essa")
regions               <- c("cssa", "noaf+mide+afg+omn+yem", "arm+aze+geo+kgz+mda+tjk+tkm+ukr+uzb", "wssa", "seas+ocea+ocex+-asm-fji-kir-wsm-ton", "sssa", 
                           "ansa-col-ven", "cub+dma+dom+grd+hti+jam+lca+vct+vir", "blz+col+cri+slv+gtm+hnd+mex+nic+pan+ven", "eaas", "soas+soax+pak-syc", "trsa", "essa+syc-yem")
ad0_map_region_titles <- c("Central Sub-Saharan Africa", "North Africa Middle East", "Central Asia Eastern Europe", "Western Sub-Saharan Africa", "Oceania", "Southern Sub-Saharan Africa", 
                           "Andean South America", "Caribbean", "Central America", "East Asia", "South Asia", "Tropical South America", "Eastern Sub-Saharan Africa")

dt_region_titles <- data.table(ad0_map_regions, regions, ad0_map_region_titles)
indicators       <- c("dpt3_cov" = "DPT3", "dpt1_cov" = "DPT1", "hib3_cov" = "Hib3", "hib3_ratio" = "Hib3 Ratio", 
                      "hepb3_cov" = "HepB3", "hepb3_ratio" = "HepB3 Ratio", "mcv1_cov" = "MCV1_cov", 
                      "polio3_cov" = "Polio3", "pcv3_cov" = "PCV3")

# Variables
indicator_group   <- "vaccine"
save_date         <- format(lubridate::with_tz(Sys.time(), tzone="America/Los_Angeles"), "%Y-%m-%d")
raked_and_unraked <- F

# File Paths
share_dir <- paste0("FILEPATH")
in_dir    <- paste0("FILEPATH")

in_file_ad0 <- paste0(in_dir, indicator, "_admin_0_raked_summary.csv")
in_file_ad1 <- paste0(in_dir, indicator, "_admin_1_raked_summary.csv")
in_file_ad2 <- paste0(in_dir, indicator, "_admin_2_raked_summary.csv")


# ---PREPARE INPUTS-----------------------------------------------------------------------------------------------

# Post-Model
ad0_df <- fread(in_file_ad0)
ad1_df <- fread(in_file_ad1)
ad2_df <- fread(in_file_ad2)

# Drop Ma'tan al-Sarra if present
ad0_df <- subset(ad0_df, ADM0_CODE != 40762)
ad1_df <- subset(ad1_df, ADM0_CODE != 40762)
ad2_df <- subset(ad2_df, ADM0_CODE != 40762)


if(raked_and_unraked){
  
  ad0_df[ ,run := "RAKED"]
  ad1_df[ ,run := "RAKED"]
  ad2_df[ ,run := "RAKED"]
  
  # Unraked 
  in_file_ad0_ur <- paste0(in_dir, indicator, "_admin_0_unraked_summary.csv")
  in_file_ad1_ur <- paste0(in_dir, indicator, "_admin_1_unraked_summary.csv")
  in_file_ad2_ur <- paste0(in_dir, indicator, "_admin_2_unraked_summary.csv")
  
  
  ad0_df_ur <- fread(in_file_ad0_ur)
  ad1_df_ur <- fread(in_file_ad1_ur)
  ad2_df_ur <- fread(in_file_ad2_ur)
  
  # Drop Ma'tan al-Sarra if present
  ad0_df_ur <- subset(ad0_df_ur, ADM0_CODE != 40762)
  ad1_df_ur <- subset(ad1_df_ur, ADM0_CODE != 40762)
  ad2_df_ur <- subset(ad2_df_ur, ADM0_CODE != 40762)
  
  ad0_df_ur[ ,run := "UNRAKED"]
  ad1_df_ur[ ,run := "UNRAKED"]
  ad2_df_ur[ ,run := "UNRAKED"]
  
  ad0_df <- rbind(ad0_df, ad0_df_ur, fill=T)
  ad1_df <- rbind(ad1_df, ad1_df_ur, fill=T)
  ad2_df <- rbind(ad2_df, ad2_df_ur, fill=T)
}


# Load Gaul shapefiles - using "africa" background map 
ad0_shape <- readOGR(get_admin_shapefile(admin_level = 0, version = "DATE"))
ad1_shape <- readOGR(get_admin_shapefile(admin_level = 1, version = "DATE"))
ad2_shape <- readOGR(get_admin_shapefile(admin_level = 2, version = "DATE"))



# ---SUBNATIONAL TIME SERIES PLOT LOOP--------------------------------------------------------------

for (region in dt_region_titles$ad0_map_regions) {
  
  vax_region_abbreviation <- region
  region_code             <- dt_region_titles[ad0_map_regions == vax_region_abbreviation, regions]
  title                   <- dt_region_titles[ad0_map_regions == vax_region_abbreviation, ad0_map_region_titles]
  region_abbreviation     <- gsub(pattern = "vax_", replacement = "", vax_region_abbreviation)
  out_dir                 <- paste0(file.path("FILEPATH")
  
  if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)
  
  # Temp
  
  
  input_data_file_path <- file.path("FILEPATH"))
  input_data <- fread(input_data_file_path)
  
  message("Beginning: ", title, "\n\n")
  
  source('FILEPATH')
  
  input_dat <- input_aggregate_admin(indicator,
                                     indicator_group,
                                     regions = region_code,
                                     run_date = run_date,
                                     input_data = input_data,
                                     indicator_family = "binomial",
                                     svy_id = "svy_id",
                                     sample_column = "SSW",
                                     subnational_nids = NULL,
                                     shapefile_version = 'DATE') 

  
    ## FUNCTION CALL
  subnational_ts_plots(ad0_df,
                       ad1_df,
                       ad2_df,
                       # ^ Model outputs
                       ad0_shape = ad0_shape,
                       ad1_shape = ad1_shape,
                       ad2_shape = ad2_shape,
                       # sigificant variable, must match run date
                       ind_title = indicators[[indicator]],
                       out_dir = out_dir,
                       out_filename_format = "subnational_ts_plots_%s.pdf",
                       val_range = c(0,1),
                       highisbad = F,
                       # Significant variable
                       ad0_map_regions = vax_region_abbreviation, 
                       ad0_map_region_titles = title, 
                       ad1_map_countries = NULL,
                       plot_levels = c("ad0", "ad1", "ad2"),
                       multiple_runs = raked_and_unraked,
                       plot_data = T,
                       # Model inputs
                       ad0_data = data.table(input_dat$ad0),
                       ad1_data = data.table(input_dat$ad1),
                       ad2_data = data.table(input_dat$ad2),
                       title_plot_size = NULL,
                       title_grob_size = NULL,
                       verbose = T,
                       shapefile_version = "2019_08_01",
                       tol = 0.001)
}

### END OF FUNCTION CALL
